### ISSUE TITLE
No .exe file available and unable to compile in VSE 2010

### ISSUE THREAD

**Issue by avcomware** [NaolShow/Wolfy#1]
Hi Naol.
I used Vocals but I am unable to send any Alt+key commands to the apps, Control and Shift work fine and I found your app. I am trying to see if I can help and create / test some profiles for Flight simulators but I am unable to compile and create an .exe file. I get an Error message about the VSE I use being too old, 2010, incompatible with your version.
Is there a source for that, or do you know a way around it?

**Comment by NaolShow** [comment]
Hello, sorry for the waiting time, I haven't developed the software for some time now (not enough time with the courses), 
so for now you can compile the application with Visual Studio 2017 (this is the version I use) available here for free: https://visualstudio.microsoft.com/fr/vs/ (Download the community edition). 

Of course, when the "official" release of the application (when it works well as a whole), the installation setup will be available, but for the moment if you want to try the software you have to compile it yourself

But for the moment Wolfy is not finished. You can still create profiles, commands (executed with an .lua file). But that's all. The commands part is quite complicated to use. I am actively resuming development! You should see several committees arrive on the project. 

Thank you and good evening (if you have any questions I'm here)
- Loan
