### ISSUE TITLE
news

### ISSUE THREAD

**Issue by Verc0rs** [NaolShow/Wolfy#2]
Hello,
I'm using Vocals but I'm interested in your project. Can we hopes an official version for this year ?
thanks

**Comment by NaolShow** [comment]
Hello, yes I know i'm slow to do the updates ^^

I'm really happy that you are interested with the project.
An official version for this year will, normaly be done.

For this new year (and Happy new year also!), I told to me that I have to work a little more on my projects and stop stopping them after few months.

I already done (already few months) a rework branch for Wolfy that you can find here: 
https://github.com/NaolShow/Wolfy/tree/rework

You should see new commits on the rework branch ^^
And also an official version comming in few months.

You can also join my discord server if you want to keep you updated on the development: 
https://discordapp.com/invite/m7CZ6md

Thanks :)

**Comment by Verc0rs** [comment]
Thanks for your answer.
And happy new year for you too !

**Comment by Verc0rs** [comment]
Thanks for your answer.
And happy new year for you too !
